### ISSUE TITLE
Does jquery.js is required ?

### ISSUE THREAD

**Issue by dyaa** [eisneim/ngFlowGrid#1]
I see you right that (no jquery dependency) and in the installation section you included the JQuery so is it required ?

**Comment by PaoJiao** [comment]
maybe he forget to update the README, lol

**Comment by eisneim** [comment]
jQuery dependency removed, but might not work for acient browsers like IE8

**Comment by ghusse** [comment]
There is still a call to jquery in the last method:

```
 $scope.$on('$destroy',function(){
     $(window).unbind('resize',false);
 });
```

Which can be replaced by:

```
 $scope.$on('$destroy',function(){
     angular.element(window).unbind('resize',false);
 });
```

**Comment by eisneim** [comment]
oh, silly me! @ghusse thanks

**Comment by ghusse** [comment]
Did you pushed a change? I cannot see it!

**Comment by eisneim** [comment]
@ghusse pushed

**Comment by ghusse** [comment]
Thanks
