### ISSUE TITLE
Order of elements not preserved

### ISSUE THREAD

**Issue by ghusse** [eisneim/ngFlowGrid#5]
Hi,

I'm trying to use ngFlowGrid, and I have a problem with the first display.

If I display a list of elements, they are displayed in the wrong order at first. If I resize the window, then the order changes (all elements are displayed in the opposite order: first elements on the left).

Is it a bug, or is it something that I'm doing wrong ?

**Comment by eisneim** [comment]
the order is left to right in each row, the last few of your item might in wrong order cause they will be used to fill in the shortest column to make sure each column is almost at same height.

**Comment by ghusse** [comment]
Hello,

I created an example here (40 elements displayed) : http://jsbin.com/jijezuwonu
The code can be edited here: http://jsbin.com/jijezuwonu/edit?html,js

As you can see by yourself, and on the screen capture, elements are not in the correct order

![capture d ecran 2015-06-30 a 23 23 48](https://cloud.githubusercontent.com/assets/527245/8442404/2557d0e6-1f7f-11e5-9c2c-77de7e1375c9.png)

If I resize the window, the display changes and now the order is right

![capture d ecran 2015-06-30 a 23 24 33](https://cloud.githubusercontent.com/assets/527245/8442420/435f6ac2-1f7f-11e5-8ce5-fea21e0f2042.png)

Even if I go back to the original screen size, the order is preserved
![capture d ecran 2015-06-30 a 23 25 18](https://cloud.githubusercontent.com/assets/527245/8442445/5a540a1c-1f7f-11e5-854c-f64b60ce2a9f.png)

**Comment by leozdgao** [comment]
@ghusse Yes, I reported the issue here before  https://github.com/eisneim/ngFlowGrid/issues/3

At first time, I think maybe the calculation of height is done before the images loaded, which cause the issue at the first rendering. But it seems not, I'll review the code in my spare time, and try to make it right.

**Comment by ghusse** [comment]
Thank you.

**Comment by eisneim** [comment]
the only solution i have in mind is:  provide a preload option, so when images are all loaded, will trigger a reflow; but the preload is some what unpredictable. what do you guys think? is there a better solution?

**Comment by ghusse** [comment]
Why does it change anything? At the beginning as images are not loaded at
all, every element have approximatively the same height. Why it that case
the code decides to put them in the "wrong" order?

**Comment by eisneim** [comment]
@ghusse i have no idea... i'll check it again when i got time  from my work

**Comment by ghusse** [comment]
Hello,

Any news about this? I still have this issue. This code could be really usefull but, because of this bug, I will not use it.

**Comment by eisneim** [comment]
@ghusse sorry for my late reply, just too busy writing React.js app don't angular haven't got my attention, and this bug is fixed;

**Comment by ghusse** [comment]
Great, thanks! I just tested and it works. :)
