### ISSUE TITLE
when items size is same, layout is not expected. 

### ISSUE THREAD

**Issue by DeepDiving2015** [eisneim/ngFlowGrid#8]
Just modify demo items src to the same, and the last col is smaller than others. 

<img width="1258" alt="snap" src="https://cloud.githubusercontent.com/assets/11802966/12028909/0be01bee-ae1a-11e5-990e-8bcd38c17aa6.png">

**Comment by eisneim** [comment]
maybe you should check your css rules, in the Demo, everything works just fine

**Comment by eisneim** [comment]
```
.flowGridColumn:last-of-type{
   /*padding-right: 10px;*/
 }
```

this should fix the issue
